In [1]:
import pandas as pd
import numpy as np

## Interviewer:

# "Suppose I give you a new dataset. What would be your approach to analyze and prepare the data for business analysis?"

🧑‍💻 Your answer:

"First, I will load the data. Then I will understand the data by checking its structure, rows, columns, data types, and summary statistics. After that, I will perform data cleaning and preprocessing, such as handling missing values, duplicates, incorrect data types, and inconsistent values. Then I will validate the cleaned data and perform Exploratory Data Analysis (EDA). Finally, I will use data visualization to identify patterns and trends and generate meaningful business insights."



1. Load Data
2. Understand Data
   - shape
   - columns
   - head()
   - info()
   - describe()

3. Data Cleaning / Preprocessing
   - Missing values
   - Duplicates
   - Wrong data types
   - Invalid values
   - Outliers

4. Exploratory Data Analysis (EDA)
   - Counts
   - GroupBy
   - Statistics
   - Correlation

5. Data Visualization
   - Bar chart
   - Histogram
   - Box plot
   - Scatter plot

6. Business Insights

In [2]:
df = pd.read_csv(r"C:\Users\user5\OneDrive\Desktop\Data science batch 23\python\DATA SETS\EMPLOYEE DATA SET\Employee.csv")

df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Education                  4653 non-null   object
 1   JoiningYear                4653 non-null   int64
 2   City                       4653 non-null   object
 3   PaymentTier                4653 non-null   int64
 4   Age                        4653 non-null   int64
 5   Gender                     4653 non-null   object
 6   EverBenched                4653 non-null   object
 7   ExperienceInCurrentDomain  4653 non-null   int64
 8   LeaveOrNot                 4653 non-null   int64
dtypes: int64(5), object(4)
memory usage: 327.3+ KB

In [9]:
# Display the first 10 employees.
df.head(10)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
8,Bachelors,2016,Pune,3,23,Male,No,1,0
9,Masters,2017,New Delhi,2,37,Male,No,2,0

In [10]:
#How many employees are there??

df.shape

(4653, 9)

In [11]:
df['Education'].count()

np.int64(4653)

In [5]:
# Display all column names..
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [7]:
#Check the data type of every column.
df.dtypes

Education                    object
JoiningYear                   int64
City                         object
PaymentTier                   int64
Age                           int64
Gender                       object
EverBenched                  object
ExperienceInCurrentDomain     int64
LeaveOrNot                    int64
dtype: object

In [12]:
# Find missing values in every column..
df.isnull().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [15]:
#Check whether duplicate records exist.
df.duplicated().any()

np.True_

In [17]:
 
#count how many duplicate records:

df.duplicated().sum()

np.int64(1889)

In [21]:
# find duplaicated row 

df[df.duplicated()]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
111,Bachelors,2017,Pune,2,27,Female,No,5,1
130,Bachelors,2017,Bangalore,3,26,Female,No,4,0
138,Bachelors,2017,New Delhi,3,28,Male,No,2,0
160,Bachelors,2014,Bangalore,3,28,Female,No,3,0
167,Bachelors,2014,Bangalore,3,25,Male,No,3,0
...,...,...,...,...,...,...,...,...,...
4640,Bachelors,2015,Bangalore,3,35,Male,No,0,0
4642,Bachelors,2012,Bangalore,3,36,Female,No,4,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [22]:
df[df.duplicated(keep=False)]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
8,Bachelors,2016,Pune,3,23,Male,No,1,0
10,Masters,2012,Bangalore,3,27,Male,No,5,1
14,Bachelors,2012,Bangalore,3,37,Male,No,4,0
...,...,...,...,...,...,...,...,...,...
4640,Bachelors,2015,Bangalore,3,35,Male,No,0,0
4642,Bachelors,2012,Bangalore,3,36,Female,No,4,0
4646,Bachelors,2013,Bangalore,3,25,Female,No,3,0
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [20]:
df.duplicated().sum()

np.int64(1889)

In [25]:
# Remove duplicate records.
df.drop_duplicates(inplace=True)

In [26]:
df.duplicated().sum()

np.int64(0)

In [31]:
# Show all unique cities.
df.City.unique()

array(['Bangalore', 'Pune', 'New Delhi'], dtype=object)

In [32]:
# how many unique cities:
df.City.nunique()

3

In [34]:
#Count employees city-wise.
df['City'].value_counts()

City
Bangalore    1171
Pune          801
New Delhi     792
Name: count, dtype: int64

In [44]:
# Count male and female employees.
df.groupby(by='Gender').size()

Gender
Female    1235
Male      1529
dtype: int64

In [45]:
# or
df['Gender'].value_counts()

Gender
Male      1529
Female    1235
Name: count, dtype: int64

In [48]:
# Show employees whose age is greater than 30.
df.Age > 40

0       False
1       False
2       False
3       False
4       False
        ...
4645    False
4647    False
4649    False
4650    False
4651    False
Name: Age, Length: 2764, dtype: bool

In [4]:
df.loc[df['Age'] > 30]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
9,Masters,2017,New Delhi,2,37,Male,No,2,0
...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

In [53]:
# or 
df[df['Age'] > 30]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
6,Bachelors,2015,New Delhi,3,38,Male,No,0,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
9,Masters,2017,New Delhi,2,37,Male,No,2,0
...,...,...,...,...,...,...,...,...,...
4641,Bachelors,2016,Bangalore,1,33,Female,No,0,1
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1

In [56]:
# Show employees from Pune.

df.loc[df['City']=='Pune']

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
1,Bachelors,2013,Pune,1,28,Female,No,3,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
8,Bachelors,2016,Pune,3,23,Male,No,1,0
11,Bachelors,2016,Pune,3,34,Male,No,3,0
12,Bachelors,2018,Pune,3,32,Male,Yes,5,1
...,...,...,...,...,...,...,...,...,...
4625,Bachelors,2013,Pune,3,37,Male,No,3,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1

In [58]:
# Show employees who have never been benched.
df.loc[df['EverBenched']=='No']

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4645,Masters,2017,Pune,2,31,Female,No,2,0
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1

In [59]:
# Find employees whose PaymentTier is 3.

df.loc[df['PaymentTier']==3]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
5,Bachelors,2016,Bangalore,3,22,Male,No,0,0
...,...,...,...,...,...,...,...,...,...
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4647,Bachelors,2016,Pune,3,30,Male,No,2,0
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0

In [65]:
df.loc[(df['Gender']=='Female') & (df ['Age'] > 28) ]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
16,Bachelors,2014,Bangalore,3,34,Female,No,2,0
18,Bachelors,2015,Pune,2,30,Female,No,0,1
28,Bachelors,2013,Pune,2,31,Female,No,2,1
...,...,...,...,...,...,...,...,...,...
4636,Masters,2014,New Delhi,3,37,Female,No,0,1
4641,Bachelors,2016,Bangalore,1,33,Female,No,0,1
4643,Bachelors,2013,Bangalore,3,31,Female,No,5,0
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4645,Masters,2017,Pune,2,31,Female,No,2,0

In [66]:
# Find employees from Bangalore having PaymentTier 2.

df[(df['City']=='Bangalore') & (df['PaymentTier'] == 2)]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
62,PHD,2013,Bangalore,2,25,Male,No,3,1
109,Bachelors,2015,Bangalore,2,25,Female,No,3,1
189,Bachelors,2013,Bangalore,2,27,Male,No,5,0
212,Masters,2013,Bangalore,2,28,Female,No,2,1
237,Masters,2017,Bangalore,2,26,Female,No,4,1
414,Masters,2015,Bangalore,2,26,Female,No,4,1
815,Masters,2017,Bangalore,2,25,Female,Yes,3,1
878,Bachelors,2017,Bangalore,2,27,Male,No,5,0
938,Masters,2017,Bangalore,2,28,Male,Yes,2,1
1176,Masters,2017,Bangalore,2,24,Female,Yes,2,1
1216,Masters,2017,Bangalore,2,28,Male,No,2,0
1256,Masters,2017,Bangalore,2,24,Male,No,2,1
1318,Bachelors,2016,Bangalore,2,25,Male,No,3,1
1473,Bachelors,2015,Bangalore,2,28,Female,No,3,1
1624,Masters,2015,Bangalore,2,27,Female,No,5,1
1661,Bachelors,2017,Bangalore,2,28,Female,No,1,0
1707,Masters,2017,Bangalore,2,26,Male,No,4,1
1751,Masters,2017,Bangalore,2,25,Male,No,3,0
1761,Bachelors,2013,Bangalore,2,24,Female,No,2,1
1772,Masters,2017,Bangalore,2,26,Female,No,4,0
1788,Masters,2017,Bangalore,2,27,Female,No,5,1
1821,Masters,2017,Bangalore,2,24,Female,No,2,0
1912,Bachelors,2014,Bangalore,2,26,Female,No,4,1
1921,Bachelors,2017,Bangalore,2,28,Female,No,2,1
1937,Masters,2017,Bangalore,2,27,Male,No,5,0
2040,Masters,2015,Bangalore,2,27,Female,Yes,5,1
2051,Bachelors,2012,Bangalore,2,27,Female,No,5,1
2129,Masters,2017,Bangalore,2,26,Male,Yes,4,1
2206,Bachelors,2013,Bangalore,2,30,Female,No,1,1
2316,Masters,2013,Bangalore,2,29,Female,No,2,1
2417,Bachelors,2015,Bangalore,2,27,Female,No,5,1
2651,Bachelors,2013,Bangalore,2,30,Male,No,0,1
2685,Bachelors,2016,Bangalore,2,30,Female,No,4,1
2692,Bachelors,2013,Bangalore,2,27,Female,No,5,1
2696,Masters,2017,Bangalore,2,30,Male,No,3,0
2729,Bachelors,2018,Bangalore,2,28,Female,No,3,1
2937,Masters,2017,Bangalore,2,27,Male,No,5,1
2944,Bachelors,2013,Bangalore,2,26,Female,No,4,1
3032,Masters,2012,Bangalore,2,32,Male,No,3,1
3122,Bachelors,2015,Bangalore,2,32,Female,No,2,1
3139,Masters,2017,Bangalore,2,41,Male,No,4,0
3290,Bachelors,2013,Bangalore,2,38,Female,No,1,1
3337,Bachelors,2015,Bangalore,2,39,Female,No,0,1
3364,Bachelors,2017,Bangalore,2,37,Male,No,2,1
3422,PHD,2013,Bangalore,2,41,Male,No,2,1
3428,Bachelors,2017,Bangalore,2,38,Female,No,5,1
3494,Bachelors,2017,Bangalore,2,32,Female,No,2,1
3504,Masters,2017,Bangalore,2,40,Female,Yes,2,0
3566,Masters,2017,Bangalore,2,39,Female,No,2,1
3646,Masters,2017,Bangalore,2,32,Male,No,2,0
3775,Masters,2017,Bangalore,2,41,Male,Yes,2,1
3925,Masters,2017,Bangalore,2,31,Male,No,5,0
3992,Bachelors,2018,Bangalore,2,26,Female,No,4,1
4028,Bachelors,2017,Bangalore,2,23,Male,No,1,0
4192,Masters,2017,Bangalore,2,35,Female,No,0,0
4201,Masters,2013,Bangalore,2,29,Male,No,1,1
4239,Bachelors,2013,Bangalore,2,25,Male,No,3,1
4243,Bachelors,2017,Bangalore,2,25,Female,No,3,1
4629,Bachelors,2017,Bangalore,2,35,Male,No,0,0

In [71]:
# Sort employees by age.

df.sort_values(by= 'Age' )

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
4393,Bachelors,2014,Bangalore,3,22,Female,No,0,0
4048,Bachelors,2014,Bangalore,3,22,Male,No,0,0
4530,Bachelors,2012,Bangalore,3,22,Male,No,0,1
4491,Bachelors,2015,Bangalore,3,22,Male,No,0,1
4284,Bachelors,2015,Pune,2,22,Female,No,0,1
...,...,...,...,...,...,...,...,...,...
3938,Bachelors,2017,New Delhi,3,41,Female,No,4,0
3958,Masters,2016,New Delhi,3,41,Female,No,4,0
3289,Bachelors,2012,Bangalore,3,41,Male,No,5,0
3914,PHD,2017,Pune,3,41,Male,No,2,0
3669,Bachelors,2012,New Delhi,3,41,Female,No,0,0

In [72]:
# Sort employees by joining year descending.
df.sort_values(by = 'JoiningYear' ,ascending = False)

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
425,PHD,2018,New Delhi,3,25,Male,No,3,1
3541,Bachelors,2018,Bangalore,3,41,Male,No,5,1
3556,Masters,2018,New Delhi,3,31,Female,Yes,2,1
2980,Bachelors,2018,New Delhi,3,30,Female,Yes,3,1
2990,Bachelors,2018,Bangalore,3,36,Male,No,2,1
...,...,...,...,...,...,...,...,...,...
3171,Bachelors,2012,Bangalore,3,41,Female,No,5,0
1779,Masters,2012,New Delhi,3,25,Male,No,3,1
3164,Bachelors,2012,Pune,3,39,Male,No,2,0
3921,Bachelors,2012,Bangalore,3,33,Male,Yes,0,0
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0

In [75]:
# Average age city-wise 
df.groupby(by = 'City') ['Age'].mean()

City
Bangalore    31.557643
New Delhi    30.233586
Pune         30.780275
Name: Age, dtype: float64

In [77]:
# Number of employees in every PaymentTier.
df.groupby(by='PaymentTier').size()

PaymentTier
1     218
2     570
3    1976
dtype: int64

In [78]:
# Count employees according to Education.

df.groupby(by='Education').size()

Education
Bachelors    1971
Masters       637
PHD           156
dtype: int64

In [83]:
# Which city has the highest employee attrition?

df[df['LeaveOrNot'] == 1 ]['City'].value_counts()

City
Bangalore    410
Pune         408
New Delhi    270
Name: count, dtype: int64

In [84]:
df[df['LeaveOrNot'] == 1 ]['City'].value_counts().idxmax()

'Bangalore'

In [85]:
# Which PaymentTier has the maximum employees leaving?

df[df['LeaveOrNot'] == 1]['PaymentTier'].value_counts().idxmax()

np.int64(3)

In [87]:
# Find the average age of employees who left.
df[df['LeaveOrNot'] == 1 ] ['Age'] .mean()

np.float64(30.22426470588235)

In [88]:
# Calculate the leave percentage.

df['LeaveOrNot'].mean() * 100

np.float64(39.36324167872648)

In [90]:
# Show city-wise attrition rate.

df.groupby(by='City')['LeaveOrNot'].mean()

City
Bangalore    0.350128
New Delhi    0.340909
Pune         0.509363
Name: LeaveOrNot, dtype: float64

In [91]:
# Show city-wise attrition rate.

df.groupby(by='City')['LeaveOrNot'].mean()*100

City
Bangalore    35.012810
New Delhi    34.090909
Pune         50.936330
Name: LeaveOrNot, dtype: float64

In [97]:
# Find employees who were never benched but still left.
df[(['EverBenched']=='No') | (df ['LeaveOrNot']==1)]

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
1,Bachelors,2013,Pune,1,28,Female,No,3,1
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
7,Bachelors,2016,Bangalore,3,34,Female,No,2,1
10,Masters,2012,Bangalore,3,27,Male,No,5,1
...,...,...,...,...,...,...,...,...,...
4639,Bachelors,2017,Bangalore,3,28,Male,No,0,1
4641,Bachelors,2016,Bangalore,1,33,Female,No,0,1
4644,Bachelors,2015,Pune,3,32,Female,Yes,1,1
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1

In [98]:
# Compare male vs female attrition.
df.groupby('Gender')['LeaveOrNot'].mean() * 100

Gender
Female    49.716599
Male      31.000654
Name: LeaveOrNot, dtype: float64

In [103]:
# Which city has the youngest employees?
df.groupby(by='City') ['Age'] .min().idxmin()

'Bangalore'

In [104]:
# Which city has the most experienced employees?
df.groupby(by='City') ['ExperienceInCurrentDomain'] .max().idxmax()

'Bangalore'

In [ ]:
# Find the top 10 oldest employees.
df.sort_values('Age', ascending=False).head(10)

In [5]:
df.columns

Index(['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender',
       'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot'],
      dtype='object')

In [6]:
df

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1
...,...,...,...,...,...,...,...,...,...
4648,Bachelors,2013,Bangalore,3,26,Female,No,4,0
4649,Masters,2013,Pune,2,37,Male,No,2,1
4650,Masters,2018,New Delhi,3,27,Male,No,5,1
4651,Bachelors,2012,Bangalore,3,30,Male,Yes,2,0
4652,Bachelors,2015,Bangalore,3,33,Male,Yes,4,0

# Business Problem: Employee Attrition Analysis

# Q1. What is the overall employee attrition rate?
👨‍💼 Interviewer:

# "Can you tell me what percentage of employees have left the company?"

🧑‍💻 Your answer:

"Yes. I would calculate the mean of the LeaveOrNot column because it contains binary values, where 1 represents employees who left and 0 represents employees who stayed. Multiplying the mean by 100 gives me the attrition percentage."

In [9]:
 df['LeaveOrNot'].mean() * 100

np.float64(34.38641736514077)

# Q2. Which city has the highest employee attrition rate?
👨‍💼 Interviewer:

"Which city has the highest employee attrition rate?"

🧑‍💻 Your answer:

"I would group the employees by city and calculate the mean of LeaveOrNot. Since LeaveOrNot is binary, the mean represents the attrition rate."

In [12]:
df.groupby(by='City')['LeaveOrNot'].mean()

City
Bangalore    0.267056
New Delhi    0.316335
Pune         0.503943
Name: LeaveOrNot, dtype: float64

# Q3. Which Payment Tier has the highest attrition?
👨‍💼 Interviewer:

"Can you identify which payment tier has the highest employee attrition?"

🧑‍💻 Your answer:

"Yes. I would group employees by payment tier and calculate the attrition rate for each tier."

In [14]:
df.groupby(by='PaymentTier')['LeaveOrNot'].mean()

PaymentTier
1    0.366255
2    0.599129
3    0.275200
Name: LeaveOrNot, dtype: float64

In [15]:
df.groupby(by='City')['LeaveOrNot'].mean().sort_values(ascending=False)

City
Pune         0.503943
New Delhi    0.316335
Bangalore    0.267056
Name: LeaveOrNot, dtype: float64